In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32)
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [3]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [4]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [5]:
inputs = tf.random.normal(shape=(1,3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.03791079, 0.89254063, 0.7987215 ]], dtype=float32)>

In [6]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.18213229, 0.4281027 , 0.389765  ]], dtype=float32)>

In [7]:
outputs.numpy()

array([[0.18213229, 0.4281027 , 0.389765  ]], dtype=float32)