In [1]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
iris

In [4]:
import pandas as pd
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [5]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_iris.to_sql('iris_resource', connect, if_exists='append', index=False)

In [ ]:
df_load = pd.read_sql_query('select * from iris_resource', connect)
df_load.head(4)

In [7]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [8]:
import numpy as np

In [9]:
y_data = iris.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

In [10]:
import tensorflow as tf

In [11]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(4,))) # input layer
model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden layer
model.add(tf.keras.layers.Dense(24, activation='relu')) # hidden layer
model.add(tf.keras.layers.Dense(3, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='mse', metrics=['acc'], ) # gadget

In [ ]:
model.summary()

In [ ]:
model.fit(x_data, y_data, epochs=50, validation_split=0.3) # 학습

# Evaluation

In [14]:
model.evaluate(x_data, y_data)

5/5 [==============================] - 0s 2ms/step - loss: 1.1112 - acc: 0.4800


[1.1112147569656372, 0.47999998927116394]

# service

In [16]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [17]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.33073446, 0.33248967, 0.33677584]], dtype=float32)

In [19]:
import numpy as np
np.argmax(pred)

2