In [23]:
import tensorflow as tf

In [24]:
loaded_model = tf.keras.models.load_model('./NaverSentimentAnalysis_LSTM.h5')
loaded_model

In [ ]:
!python -m pip install konlpy

In [26]:
import konlpy

In [41]:
words = list()
for tok in temp_x:
  if tok not in stopwords:
    words.append(tok)

NameError: ignored

In [28]:
import pickle

In [29]:
stopwords = pickle.load(open('./stopwords.pkl','rb'))
print(stopwords)

['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']


In [30]:
# 감독이 예술이네. --> 웹 사용자 입력.
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
new_sentence

['감독', '예술', '이네', '.']

In [31]:
tokenizer = pickle.load(open('./tokenizer.pkl', 'rb'))
tokenizer

In [32]:
# encoded = tokenizer.texts_to_sequences([new_sentence])
# encoded
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   2, 128,   1]],
      dtype=int32)

In [33]:
# ['감독이 예술이네.']
score = loaded_model.predict(pad_new)
score

array([[0.5086168]], dtype=float32)

In [34]:
if(score > 0.5):
  print('긍정',score*100)
else :
  print('부정',score*100)

긍정 [[50.86168]]


In [35]:
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('이 영화 꽝이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
encoded = tokenizer.texts_to_sequences([new_sentence])
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
score = loaded_model.predict(pad_new)

In [36]:
def sentiment_predict(sentence):
  okt = konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)  
  return score

In [37]:
words = '이 영화 꽝이네.'
sentiment_predict(words)

array([[0.5086168]], dtype=float32)

In [38]:
words = '영화가 좋으니 마음도 좋네요'
sentiment_predict(words)

array([[0.5115166]], dtype=float32)