In [41]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [42]:
note_seq[0:5]

['g8', 'e8', 'e4', 'f8', 'd8']

In [43]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [44]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [45]:
len(note_seq), range(len(note_seq)-4) # [4,8,12,....]

(54, range(0, 50))

In [46]:
code2idx['g8']

11

In [47]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [48]:
import numpy as np
datasets = np.array(dataset)

In [49]:
x_train = datasets[:,0:3]
x_train.shape, #x_train

((50, 3),)

In [50]:
y_train = datasets[:,3]
y_train.shape, #y_train

((50,),)

In [51]:
len(code2idx)

14

In [52]:
x_train = x_train / 13 # len(code2idx)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [53]:
import tensorflow as tf

In [54]:
x_train.shape, x_train[2] # --> scale

((50, 3), array([0.15384615, 0.76923077, 0.61538462]))

In [55]:
X_train = np.reshape(x_train, (-1, 3, 1)) # tensor
X_train.shape, X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [56]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [57]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(3,1))) # input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [58]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10) # 50 / 5 = 10

In [67]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 8ms/step - loss: 1.1114 - accuracy: 0.5200


[1.111443281173706, 0.5199999809265137]

In [60]:
X_train[0:1]

array([[[0.84615385],
        [0.69230769],
        [0.15384615]]])

In [61]:
model.predict(X_train[0:1])

array([[2.9643302e-06, 7.4745831e-03, 4.8018996e-02, 7.3415861e-03,
        9.3813399e-03, 1.8658623e-06, 2.6711750e-06, 2.1142901e-01,
        5.9192404e-02, 1.5821660e-01, 4.7673216e-01, 2.2202550e-02,
        3.2717214e-06]], dtype=float32)

In [62]:
first = 0.61538462
second = 0.07692308
third = 0.53846154

In [63]:
pred = model.predict(X_train[0:1])

In [64]:
np.argmax(pred)

10

In [65]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [66]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']